FROM apache/airflow:2.9.3

# Installation des dépendances métier nécessaires aux DAGs
# Ces packages sont utilisés par les scripts ingestion/ appelés en subprocess
USER airflow
RUN pip install --no-cache-dir \
    asyncpg==0.29.0 \
    httpx==0.27.0 \
    beautifulsoup4==4.12.3 \
    lxml==5.2.1 \
    psycopg2-binary==2.9.9
